// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: elasticcdc.proto
#ifndef GRPC_elasticcdc_2eproto__INCLUDED
#define GRPC_elasticcdc_2eproto__INCLUDED

#include "elasticcdc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace elasticcdc {

// The greeting service definition.
class ElasticcdcService final {
 public:
  static constexpr char const* service_full_name() {
    return "elasticcdc.ElasticcdcService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>> DataTransStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>>(DataTransStreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>> AsyncDataTransStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>>(AsyncDataTransStreamRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>> PrepareAsyncDataTransStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>>(PrepareAsyncDataTransStreamRaw(context, cq));
    }
    virtual ::grpc::Status IsPreempted(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest& request, ::elasticcdc::ElasticcdcReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::elasticcdc::ElasticcdcReply>> AsyncIsPreempted(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::elasticcdc::ElasticcdcReply>>(AsyncIsPreemptedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::elasticcdc::ElasticcdcReply>> PrepareAsyncIsPreempted(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::elasticcdc::ElasticcdcReply>>(PrepareAsyncIsPreemptedRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void DataTransStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::elasticcdc::ElasticcdcRequest,::elasticcdc::ElasticcdcReply>* reactor) = 0;
      virtual void IsPreempted(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest* request, ::elasticcdc::ElasticcdcReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void IsPreempted(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest* request, ::elasticcdc::ElasticcdcReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>* DataTransStreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>* AsyncDataTransStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>* PrepareAsyncDataTransStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::elasticcdc::ElasticcdcReply>* AsyncIsPreemptedRaw(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::elasticcdc::ElasticcdcReply>* PrepareAsyncIsPreemptedRaw(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>> DataTransStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>>(DataTransStreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>> AsyncDataTransStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>>(AsyncDataTransStreamRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>> PrepareAsyncDataTransStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>>(PrepareAsyncDataTransStreamRaw(context, cq));
    }
    ::grpc::Status IsPreempted(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest& request, ::elasticcdc::ElasticcdcReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::elasticcdc::ElasticcdcReply>> AsyncIsPreempted(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::elasticcdc::ElasticcdcReply>>(AsyncIsPreemptedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::elasticcdc::ElasticcdcReply>> PrepareAsyncIsPreempted(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::elasticcdc::ElasticcdcReply>>(PrepareAsyncIsPreemptedRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void DataTransStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::elasticcdc::ElasticcdcRequest,::elasticcdc::ElasticcdcReply>* reactor) override;
      void IsPreempted(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest* request, ::elasticcdc::ElasticcdcReply* response, std::function<void(::grpc::Status)>) override;
      void IsPreempted(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest* request, ::elasticcdc::ElasticcdcReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>* DataTransStreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>* AsyncDataTransStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>* PrepareAsyncDataTransStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::elasticcdc::ElasticcdcReply>* AsyncIsPreemptedRaw(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::elasticcdc::ElasticcdcReply>* PrepareAsyncIsPreemptedRaw(::grpc::ClientContext* context, const ::elasticcdc::ElasticcdcRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DataTransStream_;
    const ::grpc::internal::RpcMethod rpcmethod_IsPreempted_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status DataTransStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::elasticcdc::ElasticcdcReply, ::elasticcdc::ElasticcdcRequest>* stream);
    virtual ::grpc::Status IsPreempted(::grpc::ServerContext* context, const ::elasticcdc::ElasticcdcRequest* request, ::elasticcdc::ElasticcdcReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_DataTransStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DataTransStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DataTransStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataTransStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::elasticcdc::ElasticcdcReply, ::elasticcdc::ElasticcdcRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDataTransStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::elasticcdc::ElasticcdcReply, ::elasticcdc::ElasticcdcRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_IsPreempted : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_IsPreempted() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_IsPreempted() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPreempted(::grpc::ServerContext* /*context*/, const ::elasticcdc::ElasticcdcRequest* /*request*/, ::elasticcdc::ElasticcdcReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIsPreempted(::grpc::ServerContext* context, ::elasticcdc::ElasticcdcRequest* request, ::grpc::ServerAsyncResponseWriter< ::elasticcdc::ElasticcdcReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DataTransStream<WithAsyncMethod_IsPreempted<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DataTransStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DataTransStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->DataTransStream(context); }));
    }
    ~WithCallbackMethod_DataTransStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataTransStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::elasticcdc::ElasticcdcReply, ::elasticcdc::ElasticcdcRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>* DataTransStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_IsPreempted : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_IsPreempted() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::elasticcdc::ElasticcdcRequest* request, ::elasticcdc::ElasticcdcReply* response) { return this->IsPreempted(context, request, response); }));}
    void SetMessageAllocatorFor_IsPreempted(
        ::grpc::MessageAllocator< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_IsPreempted() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPreempted(::grpc::ServerContext* /*context*/, const ::elasticcdc::ElasticcdcRequest* /*request*/, ::elasticcdc::ElasticcdcReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IsPreempted(
      ::grpc::CallbackServerContext* /*context*/, const ::elasticcdc::ElasticcdcRequest* /*request*/, ::elasticcdc::ElasticcdcReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_DataTransStream<WithCallbackMethod_IsPreempted<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DataTransStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DataTransStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DataTransStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataTransStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::elasticcdc::ElasticcdcReply, ::elasticcdc::ElasticcdcRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_IsPreempted : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_IsPreempted() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_IsPreempted() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPreempted(::grpc::ServerContext* /*context*/, const ::elasticcdc::ElasticcdcRequest* /*request*/, ::elasticcdc::ElasticcdcReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DataTransStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DataTransStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DataTransStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataTransStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::elasticcdc::ElasticcdcReply, ::elasticcdc::ElasticcdcRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDataTransStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_IsPreempted : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_IsPreempted() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_IsPreempted() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPreempted(::grpc::ServerContext* /*context*/, const ::elasticcdc::ElasticcdcRequest* /*request*/, ::elasticcdc::ElasticcdcReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIsPreempted(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DataTransStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DataTransStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->DataTransStream(context); }));
    }
    ~WithRawCallbackMethod_DataTransStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataTransStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::elasticcdc::ElasticcdcReply, ::elasticcdc::ElasticcdcRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* DataTransStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_IsPreempted : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_IsPreempted() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->IsPreempted(context, request, response); }));
    }
    ~WithRawCallbackMethod_IsPreempted() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPreempted(::grpc::ServerContext* /*context*/, const ::elasticcdc::ElasticcdcRequest* /*request*/, ::elasticcdc::ElasticcdcReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IsPreempted(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_IsPreempted : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_IsPreempted() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::elasticcdc::ElasticcdcRequest, ::elasticcdc::ElasticcdcReply>* streamer) {
                       return this->StreamedIsPreempted(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_IsPreempted() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status IsPreempted(::grpc::ServerContext* /*context*/, const ::elasticcdc::ElasticcdcRequest* /*request*/, ::elasticcdc::ElasticcdcReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedIsPreempted(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::elasticcdc::ElasticcdcRequest,::elasticcdc::ElasticcdcReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_IsPreempted<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_IsPreempted<Service > StreamedService;
};

}  // namespace elasticcdc


#endif  // GRPC_elasticcdc_2eproto__INCLUDED
